kernel:
  image: linuxkit/kernel:5.10.104
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0 console=ttysclp0"
init:
  - linuxkit/init:8f1e6a0747acbbb4d7e24dc98f97faa8d1c6cec7
  - linuxkit/runc:f01b88c7033180d50ae43562d72707c6881904e4
  - linuxkit/containerd:de1b18eed76a266baa3092e5c154c84f595e56da
  - linuxkit/ca-certificates:c1c73ef590dffb6a0138cf758fe4a4305c9864f4
onboot:
  - name: sysctl
    image: linuxkit/sysctl:bdc99eeedc224439ff237990ee06e5b992c8c1ae
  - name: sysfs
    image: linuxkit/sysfs:c3bdb00c5e23bf566d294bafd5f7890ca319056f
  - name: format
    image: linuxkit/format:7efa07559dd23cb4dbebfd3ab48c50fd33625918
  - name: mount
    image: linuxkit/mount:422b219bb1c7051096126ac83e6dcc8b2f3f1176
    command: ["/usr/bin/mountie", "/var/lib/docker"]
  - name: mount
    image: linuxkit/mount:422b219bb1c7051096126ac83e6dcc8b2f3f1176
    command: ["sh", "-c", "mkdir /var/lib/share && mount -t virtiofs share /var/lib/share"]
services:
  - name: getty
    image: linuxkit/getty:76951a596aa5e0867a38e28f0b94d620e948e3e8
    env:
     - INSECURE=true
    binds.add:
     - /etc/profile.d/local.sh:/etc/profile.d/local.sh
  - name: rngd
    image: linuxkit/rngd:4f85d8de3f6f45973a8c88dc8fba9ec596e5495a
  - name: dhcpcd
    image: linuxkit/dhcpcd:52d2c4df0311b182e99241cdc382ff726755c450
  - name: ntpd
    image: linuxkit/openntpd:d6c36ac367ed26a6eeffd8db78334d9f8041b038
  - name: docker
    image: docker:20.10.21-dind
    capabilities:
     - all
    net: host
    devices:
      - path: "/dev/console"
        type: "c"
        major: 5
        minor: 1
        mode: "0666"
      - path: all
        type: b
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /var/lib/share:/var/lib/share
     - /lib/modules:/lib/modules
     - /var/run/docker:/var/run #- /var/run:/var/run
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: [
      "/usr/local/bin/docker-init", "/usr/local/bin/dockerd",
      "--", "--tls=false"
    ]
    runtime:
      mkdir:
        - /var/run/docker

files:
  - path: var/lib/docker
    directory: true
  - path: etc/docker/daemon.json
    contents: '{"debug": true, "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"]}'
    mode: "0600"
    optional: true
  - path: etc/profile.d/local.sh
    contents: |
      alias docker='ctr -n services.linuxkit tasks exec --tty --exec-id cmd docker docker'
      alias docker-shell='ctr -n services.linuxkit tasks exec --tty --exec-id shell docker sh'
    mode: "0644"
